sudo: false
language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.5
    env: TOXENV=flake8
  - python: pypy3.5
    env: TOXENV=pypy
install:
- pip install tox
script: tox
after_success:
- pip install codecov
- codecov -e TOXENV TRAVIS_OS_NAME
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: "dvatterott"
  password:
    secure: Edplgu14/v2GjWCGe0NC+Jnn5oqtdbN/ydJNXVjWbqc9Qs10Y3QEF54QsKn4DFdYQD6sikX90k2mhXeH5wbRPN2RiuH2LWHvl5Dwr7wTZEIgnmoVReNo7+KsAc7l3Wqt75TJ7UH9MuBHBqkBkGEowC/Mj0rrgLgJMUIHlp329qD2UkglGRG8VkwdNDCBboSRE5fF3V2MfhtHlv1AR63gyjO7t1bchM/Rxkol0hGXFeEs1wUNC76oYpYAtearN56lGVVX44xMI04icPpwymuIpxv6Ej31hhaw9b/97IqM1p7j3R0uG4kepOYDBZ7SAMm79prmWyUdCbFR3e9QQNlgBGfD5TrZwxEA371C9sG3P2joIAgl4QVT99dU+nfSOnflSnz8KRI13bZsmdhELwX25gc4n3Y4mx+Fp8ZdCXUYiZCm+eKP3oYgPgHXnu1Tg3FG1aNRKFWIyvBQBTRIVohNjrRH+fUDozO63bwO3yfbYwN1MRLbjc+Pq7xudmoqo+J03ljMjglJLL1dihAtFOwWLIf8MyEqz9mQ0kgWZM8e1yZpB5zbE75q8MM/DTN49RokjEMvtCArCpa9hLJ4eIu4vtsjYEyex/Ypg2lmfDoFX9yY1/9GZBWo2oxpuKd6iH5h6REQ95EhVuIl5BlrXMHwS2ytKFduIlblCN7yXYKe8q8=
