sudo: false
language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  # - python: pypy
  #   env: TOXENV=pypy
  - python: 3.5
    env: TOXENV=flake8
install:
  - pip install tox
script: tox
after_success:
- pip install codecov
- codecov -e TOXENV TRAVIS_OS_NAME
# deploy:
#   password:
#     secure: e1ryoJq9qgVj0htRvzOkW8hfNw0Co8JbsdKa+6LKCbi12l9EFovwbxJZj1laYc5UxeFOT6Y8DuKLEK+Ue3iCtV2GtELoszOchGd6H4iHU1RITiADYIdGJ+HBFZ1ZEC0OzlLBN6CObPDQ/y3fESBmxq0lvGycSumxmZJKx00f/bG5Y/JqMQWTRmuIOe6PsJb5v1ar4Eu+XqNu+YAL63uZaZiiJgd9On+NW8Rj9SNdVLnjOjFwmnNft+rMVXwItFOdgxt+I4ms3w9DSJA/+/+KgTwMJO5FHE+TXk7aQHpOg5/40Rm/oC4YFbQNCYgIJRd6XBn1BGvixiuEdWm231gcUoDRI9Ja3b+ndd4DhEjY4LH2AoY6BsfgrAEBmHyJdaksVKvg8IYy7hPGoFR/Bctr2CHO14ZV/tbYUMDosXDgvI0sjkESEIZsuIidUD5uoZdFaZWfEGhGlkuU5aFDNILq7wsox106Hq3Cix4XX5dZ3TsTzzWkOyZyOgCC7XtTtQLwh7BYh+KurnbTgFw2lDSFRvQ6/hGPXRzwW8XRfs1/5o0wQRC+eA4PVbrxfhc469K49+ZOcPtcHW8jDqzLoD07igoO1I4+XczhHWBKq/4GXL530I5TNrp+xIs8U3abFMTGuRX6NxpjlA3IbMdUkB/zoLHpPorsDaJ4rQeuFQh2pwI=
